const itadStores = {
        game2: {
            id: 'game2',
            title: '2game',
            barter_vg_id: 73,
        },
        allyouplay: {
            id: 'allyouplay',
            title: 'AllYouPlay',
            barter_vg_id: 141,
        },
        amazonus: {
            id: 'amazonus',
            title: 'Amazon',
            barter_vg_id: 12,
        },
        battlenet: {
            id: 'battlenet',

            title: 'Blizzard',
            barter_vg_id: 80,
        },
        dlgamer: {
            id: 'dlgamer',

            title: 'DLGamer',
            barter_vg_id: 42,
        },
        direct2drive: {
            id: 'direct2drive',

            title: 'Direct2Drive',
            barter_vg_id: 74,
        },
        dreamgame: {
            id: 'dreamgame',

            title: 'Dreamgame',
            barter_vg_id: 75, // ? dreamgate?
        },
        epic: {
            id: 'epic',

            title: 'Epic Game Store',
            barter_vg_id: 66,
        },
        bundlestars: {
            id: 'bundlestars',

            title: 'Fanatical',
            barter_vg_id: 8,
        },
        fireflower: {
            id: 'fireflower',

            title: 'FireFlower',
            barter_vg_id: 0,
        },
        gog: {
            id: 'gog',

            title: 'GOG',
            barter_vg_id: 4,
        },
        gamejolt: {
            id: 'gamejolt',

            title: 'Game Jolt',
            barter_vg_id: 0,
        },
        gamebillet: {
            id: 'gamebillet',

            title: 'GameBillet',
            barter_vg_id: 144,
        },
        impulse: {
            id: 'impulse',

            title: 'GameStop PC',
            barter_vg_id: 145,
        },
        gamersgate: {
            id: 'gamersgate',

            title: 'GamersGate',
            barter_vg_id: 11,
        },
        gamesplanetde: {
            id: 'gamesplanetde',

            title: 'GamesPlanet DE',
            barter_vg_id: 43,
        },
        gamesplanetfr: {
            id: 'gamesplanetfr',

            title: 'GamesPlanet FR',
            barter_vg_id: 43,
        },
        gamesplanet: {
            id: 'gamesplanet',

            title: 'GamesPlanet UK',
            barter_vg_id: 43,
        },
        gamesplanetus: {
            id: 'gamesplanetus',

            title: 'GamesPlanet US',
            barter_vg_id: 43,
        },
        gamesrepublic: {
            id: 'gamesrepublic',

            title: 'GamesRepublic',
            barter_vg_id: 72,
        },
        gamesload: {
            id: 'gamesload',

            title: 'Gamesload',
            barter_vg_id: 207,
        },
        greenmangaming: {
            id: 'greenmangaming',

            title: 'GreenManGaming',
            barter_vg_id: 20,
        },
        humblestore: {
            id: 'humblestore',

            title: 'Humble Store',
            barter_vg_id: 13,
        },
        humblewidgets: {
            id: 'humblewidgets',

            title: 'Humble Widgets',
            barter_vg_id: 13,
        },
        indiegalastore: {
            id: 'indiegalastore',

            title: 'IndieGala Store',
            barter_vg_id: 7,
        },
        itchio: {
            id: 'itchio',

            title: 'Itch.io',
            barter_vg_id: 28,
        },
        joybuggy: {
            id: 'joybuggy',

            title: 'JoyBuggy',
            barter_vg_id: 0,
        },
        macgamestore: {
            id: 'macgamestore',

            title: 'MacGameStore',
            barter_vg_id: 22,
        },
        microsoft: {
            id: 'microsoft',

            title: 'Microsoft Store',
            barter_vg_id: 133,
        },
        newegg: {
            id: 'newegg',

            title: 'Newegg',
            barter_vg_id: 76,
        },
        noctre: {
            id: 'noctre',

            title: 'Noctre',
            barter_vg_id: 0, // no match
        },
        nuuvem: {
            id: 'nuuvem',

            title: 'Nuuvem',
            barter_vg_id: 21,
        },
        origin: {
            id: 'origin',

            title: 'Origin',
            barter_vg_id: 0,
        },
        squenix: {
            id: 'squenix',

            title: 'Square Enix',
            barter_vg_id: 37,
        },
        steam: {
            id: 'steam',

            title: 'Steam',
            barter_vg_id: 1,
        },
        uplay: {
            id: 'uplay',

            title: 'Ubisoft Store',
            barter_vg_id: 14,
        },
        voidu: {
            id: 'voidu',

            title: 'Voidu',
            barter_vg_id: 122,
        },
        wingamestore: {
            id: 'wingamestore',

            title: 'WinGameStore',
            barter_vg_id: 34,
        },
        etailmarket: {
            id: 'etailmarket',

            title: 'eTail.Market',
            barter_vg_id: 0,
        },
    },
    bartervg = {
        0: { name: '', icon: 'unspecified2.png' },
        73: { name: '2game', icon: '2game.png' },
        211: { name: '3Kropki.pl', icon: '3kropki.png' },
        48: { name: '99 Cent Bundle', icon: '99cent.png' },
        124: { name: 'akens.ru', icon: 'akens.png' },
        131: { name: 'Alienware', icon: 'alienware.png' },
        141: { name: 'Allyouplay', icon: 'allyouplay.png' },
        134: { name: 'Alpha Bundle', icon: 'alphabundle.png' },
        12: { name: 'Amazon', icon: 'amazon.png' },
        184: { name: 'AMD Rewards', icon: 'amd.png' },
        176: { name: 'Apple', icon: 'apple.png' },
        147: { name: 'ArenaNet', icon: 'arenanet.png' },
        165: { name: 'Bananagiveaway.com', icon: 'bananag.png' },
        194: { name: 'BANDAI NAMCO', icon: 'bandai.png' },
        57: { name: 'Barter.vg', icon: 'barter.png' },
        80: { name: 'battle.net', icon: 'battlenet.png' },
        142: { name: 'Best Buy', icon: 'bestbuy.png' },
        148: { name: 'Bethesda.net', icon: 'bethesda.png' },
        120: { name: 'Bitcoin Bundle', icon: 'bitcoin.png' },
        87: { name: 'Blink Bundle', icon: 'blinkbundle.png' },
        50: { name: 'Bread Box Bundle', icon: 'breadbox.png' },
        137: { name: 'BrightLocker', icon: 'brightlocker.png' },
        45: { name: 'Bunch of Keys', icon: 'bunchkeys.png' },
        89: { name: 'Bundle Bandits', icon: 'bbandits.png' },
        90: { name: 'Bundle Central', icon: 'bcentral.png' },
        91: { name: 'Bundle Dragon', icon: 'bdragon.png' },
        92: { name: 'Bundle In A Box', icon: 'biab.png' },
        39: { name: 'Bundle Kings', icon: 'bundlekings.png' },
        118: { name: 'Buy Games Not Socks', icon: 'socks.png' },
        59: { name: 'CDKeys.com', icon: 'cdkeys.png' },
        193: { name: 'ChampionFlow', icon: 'championflow.png' },
        117: { name: "Charlie's Games", icon: 'charlies.png' },
        41: { name: 'Chrono.gg', icon: 'chronogg.png' },
        167: { name: 'Chubkeys', icon: 'chubkeys.png' },
        224: { name: 'CJS-CDKeys', icon: 'blank.png' },
        27: { name: 'Coinplay.io', icon: 'coinplay.png' },
        222: { name: 'Corel', icon: 'corel.png' },
        226: { name: 'Crucial Games', icon: 'crucial.png' },
        31: { name: 'Cubic Bundle', icon: 'cubicbundle.png' },
        93: { name: 'Cult of Mac', icon: 'cultofmac.png' },
        109: { name: 'CY Bundle', icon: 'cybundle.png' },
        17: { name: 'DailyIndieGame', icon: 'dailyindie.png' },
        6: { name: 'Desura', icon: 'desura.png' },
        74: { name: 'Direct2Drive', icon: 'd2d.png' },
        110: { name: 'Discord', icon: 'discord.png' },
        42: { name: 'DLGamer', icon: 'dlgamer.png' },
        152: { name: 'Dlh.net', icon: 'dlhnet.png' },
        63: { name: 'DogeBundle', icon: 'dogebundle.png' },
        75: { name: 'Dreamgate', icon: 'dreamgate.png' },
        200: { name: 'dupedornot', icon: 'dupedornot.png' },
        5: { name: 'EA', icon: 'ea.png' },
        218: { name: 'Elkj&oslash;p / Elgiganten', icon: 'elgiganten.png' },
        79: { name: 'Embloo', icon: 'embloo.png' },
        210: { name: 'Eneba', icon: 'eneba.png' },
        66: { name: 'Epic Games Store', icon: 'epicgamesstore.png' },
        94: { name: 'Eurobundle', icon: 'eurobundle.png' },
        228: { name: 'F2P.com', icon: 'f2p.png' },
        8: { name: 'Fanatical', icon: 'fanatical.png' },
        84: { name: 'Fangamer', icon: 'fangamer.png' },
        125: { name: 'FarmKEYS', icon: 'farmkeys.png' },
        18: { name: 'Flying Bundle', icon: 'flyingbundle.png' },
        213: { name: 'FreeAnywhere.net', icon: 'freeanywhere2.png' },
        191: { name: 'FreeToGame.com', icon: 'freetogame.png' },
        113: { name: 'From boxed copy', icon: 'disc.png' },
        159: { name: 'From Dev / Pub', icon: 'devsource.png' },
        46: { name: 'G2A', icon: 'g2a.png' },
        83: { name: 'G2play', icon: 'g2play.png' },
        217: { name: 'Gamazavr.ru', icon: 'gamazavr.png' },
        173: { name: 'Game Junkie', icon: 'gamejunkie.png' },
        143: { name: 'GAME UK', icon: 'gameuk.png' },
        144: { name: 'Gamebillet', icon: 'gamebillet.png' },
        40: { name: 'GameBundle', icon: 'gamebundle.png' },
        162: { name: 'Gamecode.win', icon: 'gamecodewin.png' },
        177: { name: 'GameDev.tv', icon: 'gamedevtv.png' },
        221: { name: 'Gameflip', icon: 'gameflip.png' },
        227: { name: 'Gameflix.ru', icon: 'gameflixru.png' },
        149: { name: 'Gamehag', icon: 'gamehag.png' },
        155: { name: 'GAMEHUNT', icon: 'gamehunt.png' },
        103: { name: 'Gameolith', icon: 'gameolith.png' },
        233: { name: 'Gamerpower', icon: 'gamerpower.png' },
        11: { name: 'GamersGate', icon: 'gamersgate.png' },
        88: { name: 'Games Rage', icon: 'gamesrage.png' },
        72: { name: 'Games Republic', icon: 'grepublic.png' },
        201: { name: 'GamesBolt', icon: 'gamebolt.png' },
        207: { name: 'GAMESLOAD', icon: 'gamesload.png' },
        43: { name: 'Gamesplanet', icon: 'gamesplanet.png' },
        145: { name: 'GameStop', icon: 'gamestop.png' },
        164: { name: 'Gamezito', icon: 'gamezito.png' },
        216: { name: 'Gaming Dragons', icon: 'dragons.png' },
        81: { name: 'Gamivo', icon: 'gamivo.png' },
        123: { name: 'gemly', icon: 'gemly.png' },
        82: { name: 'Get Games Go', icon: 'getgames.png' },
        192: { name: 'Giveaway of the Day', icon: 'giveawayoftheday.png' },
        153: { name: 'GiveAway.su', icon: 'giveawaysu.png' },
        166: { name: 'GiveawayHopper', icon: 'ghopper.png' },
        231: { name: 'givee.club', icon: 'givee.png' },
        186: { name: 'Givekey.ru', icon: 'givekey.png' },
        154: { name: 'Gleam', icon: 'gleam.png' },
        212: { name: 'Godankey', icon: 'godankey.png' },
        4: { name: 'GOG', icon: 'gog.png' },
        58: { name: 'GoGoBundle', icon: 'gogobundles.png' },
        179: { name: 'Google', icon: 'google.png' },
        204: { name: 'Grab The Games', icon: 'grabthegame.png' },
        156: { name: 'GrabFreeGame', icon: 'grabfreegame.png' },
        95: { name: 'gram.pl', icon: 'gram.png' },
        16: { name: 'Green Light Bundle', icon: 'greenlight.png' },
        20: { name: 'Green Man Gaming', icon: 'gmg.png' },
        127: { name: 'Greenlight Arcade', icon: 'greenlighta.png' },
        9: { name: 'Groupees', icon: 'groupees3.png' },
        128: { name: 'H2O Bundle', icon: 'h2o.png' },
        232: { name: 'HitSquad Games', icon: 'hitsquad.png' },
        33: { name: 'HRK', icon: 'hrk.png' },
        3: { name: 'Humble Bundle', icon: 'humblebundle.png' },
        13: { name: 'Humble Store', icon: 'humblebundle.png' },
        85: { name: 'Humble Trove', icon: 'trove.png' },
        214: { name: 'Idle-Empire', icon: 'idle-empire.png' },
        229: { name: 'iGames.gg', icon: 'igames.png' },
        132: { name: 'IGN', icon: 'ign.png' },
        96: { name: 'Indie Ammo Box', icon: 'indieammo.png' },
        170: { name: 'Indie DB', icon: 'indiedb.png' },
        161: { name: 'Indie Face Kick', icon: 'indiefacekick.png' },
        10: { name: 'Indie Royale', icon: 'indieroyale.png' },
        115: { name: 'Indie-games pack', icon: 'igpack.png' },
        97: { name: 'IndieBundle', icon: 'iborg.png' },
        68: { name: 'IndieDeals.net', icon: 'indiedeals2.png' },
        121: { name: 'IndieFort', icon: 'gamersgate.png' },
        7: { name: 'Indiegala', icon: 'indiegala.png' },
        24: { name: 'IndieGameStand', icon: 'igamestand.png' },
        206: { name: 'Intel', icon: 'intel.png' },
        199: { name: 'io interactive', icon: 'ioi.png' },
        28: { name: 'itch.io', icon: 'itchio.png' },
        195: { name: 'Jackbox Games', icon: 'jackbox.png' },
        235: { name: 'K4G', icon: 'k4g.png' },
        220: { name: 'Kalypso Media', icon: 'kalypso.png' },
        150: { name: 'Kartridge', icon: 'kartridge.png' },
        202: { name: 'Keyhub', icon: 'keyhub.png' },
        158: { name: 'KeyJoker', icon: 'keyjoker.png' },
        223: { name: 'Keysora', icon: 'blank.png' },
        205: { name: 'Kickstarter', icon: 'kickstarter.png' },
        60: { name: 'Kinguin', icon: 'kinguin.png' },
        98: { name: 'KissMyBundles', icon: 'kissmb.png' },
        174: { name: 'Last Best Offer', icon: 'lbo.png' },
        15: { name: 'Lazy Guys Bundle', icon: 'lazyguys.png' },
        234: { name: 'Legacy Games', icon: 'legacygames.png' },
        111: { name: 'lequestore', icon: 'lequestore.png' },
        140: { name: 'Loot Crate', icon: 'lootcrate.png' },
        151: { name: 'LootBoy', icon: 'lootboy.png' },
        22: { name: 'MacGameStore', icon: 'macgamestore.png' },
        99: { name: 'MadOrc', icon: 'madorc.png' },
        56: { name: 'MarvelousCrate', icon: 'marvelous.png' },
        163: { name: 'MarvelousGA', icon: 'marvelousga.png' },
        133: { name: 'Microsoft Store', icon: 'microsoft.png' },
        187: { name: 'MMOBomb', icon: 'mmobomb.png' },
        208: { name: 'MMOGA', icon: 'mmoga.png' },
        190: { name: 'MMOGames.com', icon: 'mmogames2.png' },
        171: { name: 'MMORPG.com', icon: 'mmorpg.png' },
        76: { name: 'Newegg', icon: 'newegg.png' },
        25: { name: 'Nintendo 3DS', icon: '3ds.png' },
        183: { name: 'Nintendo Switch', icon: 'switch.png' },
        21: { name: 'Nuuvem', icon: 'nuuvem.png' },
        180: { name: 'NVIDIA', icon: 'nvidia.png' },
        185: { name: 'NVIDIA Rewards', icon: 'nvidia.png' },
        129: { name: 'Oculus', icon: 'oculus.png' },
        30: { name: 'one more bundle', icon: 'onemore.png' },
        135: { name: 'Opium Pulses', icon: 'opiumpulses.png' },
        230: { name: 'OPQuests', icon: 'opquests.png' },
        36: { name: 'Orlygift', icon: 'orlygift.png' },
        62: { name: 'Otaku Bundle', icon: 'otakubundle.png' },
        38: { name: 'OtakuMaker', icon: 'otakumaker.png' },
        197: { name: 'OVERKILL Software', icon: 'overkillsoftware.png' },
        138: { name: 'Oy Vey Keys', icon: 'oyvey2.png' },
        100: { name: 'Paddle', icon: 'paddle.png' },
        101: { name: 'PayWUW', icon: 'paywuw.png' },
        203: { name: 'PC Gamer', icon: 'pcgamer.png' },
        102: { name: 'Peon Bundle', icon: 'peonb.png' },
        64: { name: 'Plati', icon: 'plati.png' },
        23: { name: 'Playinjector', icon: 'playinjector.png' },
        225: { name: 'Playism', icon: 'playism.png' },
        52: { name: 'PlayStation 3', icon: 'ps3.png' },
        51: { name: 'PlayStation 4', icon: 'ps4.png' },
        219: { name: 'Playstation 5', icon: 'ps4.png' },
        169: { name: 'Project Z', icon: 'projectz.png' },
        188: { name: 'Prys', icon: 'prys.png' },
        78: { name: 'PSN', icon: 'ps4.png' },
        77: { name: 'PSVita', icon: 'ps3.png' },
        114: { name: 'PuppyGames', icon: 'puppygames.png' },
        130: { name: 'Razer', icon: 'razer.png' },
        49: { name: 'Redacted Network', icon: 'redacted.png' },
        112: { name: 'Rockstar Social Club', icon: 'rockstar.png' },
        198: { name: 'Running With Scissors', icon: 'rws.png' },
        104: { name: "Select n' Play", icon: 'selectnp.png' },
        105: { name: 'ShinyLoot', icon: 'shinyloot.png' },
        44: { name: 'Sila Games', icon: 'silagames.png' },
        209: { name: 'SONKWO', icon: 'sonkwo.png' },
        37: { name: 'Square Enix', icon: 'squareenix.png' },
        106: { name: 'StackSocial', icon: 'stacksocial.png' },
        139: { name: 'Stardock', icon: 'stardock.png' },
        1: { name: 'Steam', icon: 'steam.png' },
        35: { name: 'Steam Greenlight', icon: 'sgreenlight.png' },
        19: { name: 'Steam Item', icon: 'steam.png' },
        2: { name: 'Steam Package', icon: 'steam.png' },
        86: { name: 'Steam-tracker', icon: 'steam-tracker.png' },
        55: { name: 'Steamgifts.com', icon: 'steamgifts.png' },
        47: { name: 'Steamground', icon: 'steamground.png' },
        65: { name: 'Steamtrades.com', icon: 'streamtrades.png' },
        168: { name: 'SteelSeries', icon: 'steelseries.png' },
        119: { name: 'Subsoap', icon: 'subsoap.png' },
        116: { name: 'Super Shock Bundle', icon: 'supershock.png' },
        29: { name: 'Super-Duper Bundle', icon: 'superduper.png' },
        189: { name: 'Takekey.ru', icon: 'takekey.png' },
        32: { name: 'Telltale Games', icon: 'telltale.png' },
        69: { name: 'The Indie Games Bundle', icon: 'tigb.png' },
        70: { name: 'Tiltify', icon: 'tiltify.png' },
        126: { name: 'TKFG', icon: 'tkfg.png' },
        71: { name: 'Tremor Games', icon: 'tremorgames.png' },
        67: { name: 'Twitch', icon: 'twitch.png' },
        14: { name: 'Ubisoft Connect', icon: 'ubisoft.png' },
        175: { name: 'Unity Asset Store', icon: 'unity.png' },
        107: { name: 'Universala', icon: 'universala.png' },
        61: { name: 'Unspecified Platform', icon: 'unspecified2.png' },
        196: { name: 'Victorage Giveaways', icon: 'victorage.png' },
        108: { name: 'VODO', icon: 'vodo.png' },
        122: { name: 'Voidu', icon: 'voidu.png' },
        160: { name: 'WeGame X', icon: 'wegamex.png' },
        157: { name: "Who's Gaming Now?!", icon: 'wgn.png' },
        26: { name: 'WiiU', icon: 'wiiu.png' },
        34: { name: 'WinGameStore', icon: 'wingamestore.png' },
        53: { name: 'Xbox 360', icon: 'xb360.png' },
        146: { name: 'Xbox Live', icon: 'xbone.png' },
        54: { name: 'Xbox One', icon: 'xbone.png' },
        215: { name: 'Yuplay.ru', icon: 'yuplay.png' },
        172: { name: 'zeepond.com', icon: 'blank.png' },
        178: { name: 'Zenva Academy', icon: 'zenva.png' },
    };

export default function getBarterStoreIcon(itadStoreId) {
    if (itadStoreId in itadStores && 'barter_vg_id' in itadStores[itadStoreId]) {
        return bartervg[itadStores[itadStoreId].barter_vg_id].icon;
    }
    return bartervg[0].icon;
}
