name: Node.js build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
      - main
      - develop
    types:
    - opened
    - synchronize
    - ready_for_review
    - reopened

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci

    - run: npm run build

#    - run: npm test

#    - name: make bundle available as artefact
#      uses: actions/upload-artifact@v3
#      with:
#        path: dist/bundle.js

#    - name: Upload files to a GitHub release
#      uses: svenstaro/upload-release-action@2.5.0
#      with:
#        file: dist/bundle.js
